# Generated by Django 4.2.7 on 2023-12-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticepost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
