# Generated by Django 4.2.7 on 2023-12-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0002_alter_lostpost_head_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostpost',
            name='category',
            field=models.CharField(choices=[('전자기기', '전자기기'), ('지갑,카드', '지갑,카드'), ('악세사리', '악세사리'), ('화장품', '화장품'), ('기타', '기타')], max_length=20),
        ),
    ]
