# Generated by Django 4.2.7 on 2023-12-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='findpost',
            name='LostAndFound',
            field=models.TextField(max_length=15, null=True),
        ),
    ]
