# Generated by Django 4.2.7 on 2023-12-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0002_findpost_lostandfound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findpost',
            name='head_image',
            field=models.ImageField(blank=True, default='default.png', upload_to='find/images/%Y/%m/%d/'),
        ),
    ]
