# Generated by Django 4.2.7 on 2023-12-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0003_alter_findpost_head_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findpost',
            name='head_image',
            field=models.ImageField(blank=True, default='noimage.jpg', upload_to='find/images/%Y/%m/%d/'),
        ),
    ]
