# Generated by Django 4.2.7 on 2023-12-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0005_alter_findpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findpost',
            name='category',
            field=models.CharField(blank=True, choices=[('전자기기', '전자기기'), ('지갑,카드', '지갑,카드'), ('악세사리', '악세사리'), ('화장품', '화장품'), ('기타', '기타')], max_length=20, null=True),
        ),
    ]
